[tox]
envlist = py27, py35

[testenv]
deps =
    pytest
    -rrequirements.txt
commands =
    py.test {posargs}

[pytest]
minversion = 2.8
testpaths =
    Lib/ufo2ft
python_files =
    *_test.py
python_classes =
    *Test
addopts =
    # run py.test in verbose mode
    -v
    # show extra test summary info
    -r a
    # run doctests in all .py modules
    --doctest-modules
